# Generated by Django 4.2.2 on 2023-06-10 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='location',
            new_name='locations',
        ),
    ]
